spring.application.name=${COURSE_SERVICE_NAME:course-service}

server.port=${PORT:8082}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always